
#+TITLE:    Práctica No. 5
#+SUBTITLE: 
#+AUTHOR:   Luis Eduardo Galindo Amaya
#+DATE:     lunes, 20 noviembre 2023

#+OPTIONS: toc:nil ^:nil title:nil num:2
#+LANGUAGE: es

#+latex_header: \usepackage{../../modern}
#+latex_header: \bibliography{./fuentes.bib}
#+latex_header: \raggedbottom

#+macro: code @@latex:\lstinputlisting{$1}@@
#+macro: cite @@latex:\cite{$1}@@
#+macro: autocite @@latex:\autocite{$1}@@

\modentitlepage{../../images/escudo-uabc-2022-1-tinta-pos.png}
\datasection{Individual}
\tableofcontents
\pagebreak


* Introducción
{{{autocite(wiki:Aprendizaje_supervisado)}}} El aprendizaje supervisado
es una técnica en aprendizaje automático (AA) y minería de datos que
se utiliza para deducir una función a partir de datos de formación.
Los datos de formación consisten de pares de objetos 
(normalmente vectores): una componente del par son los datos de entrada
y el otro, los resultados deseados.


* Regresión
La problematicas seleccionada para el problema de regresion fue la
prediccion de ingresos semanales de una empresa (Walmart), el dataset
que se utilizará es '[[https://www.kaggle.com/datasets/yasserh/walmart-dataset][Walmart dataset]]' de kaggle, los datos que
contiene son:

#+ATTR_LATEX: :environment tabularx :width 0.8\textwidth
|   | Atributo      | Descripción                                    |
|---+---------------+------------------------------------------------|
| / | >             |                                                |
|   | Store_Number  | Número de la tienda                            |
|   | Date          | Fecha                                          |
|   | Week_of_Sales | Semana de ventas                               |
|   | Weekly_Sales  | Ventas semanales para la tienda dada           |
|   | Holiday_Flag  | Indica si la semana es especial por festividad |
|   | Temperature   | Temperatura el día de la venta                 |
|   | Fuel_Price    | Costo del combustible en la región             |
|   | CPI           | Índice de precios al consumidor predominante   |
|   | Unemployment  | Tasa de desempleo predominante                 |

El dataset seleccionado tiene columnas que muestran la cantidad de
factores que participan en los ingresos que se perciben, una regresion
lineal no permite tomar en cuenta los factores que pueden influir.


* Clasificación
El problema seleccionado para utilizar clasificación es: Detección de
riesgo de ataque cardiaco. el dataset que se va a utilizar es '[[https://www.kaggle.com/datasets/rashikrahmanpritom/heart-attack-analysis-prediction-dataset?select=heart.css][Heart Attack
Analysis & Prediction Dataset]]' de kaggle, el dataset contiene
los siguientes datos sobre los pacientes:

#+ATTR_LATEX: :environment tabularx :width 0.8\textwidth
|   | Atributo   | Descripción                                |
| / | >          |                                            |
|---+------------+--------------------------------------------|
|   | Age        | Edad del paciente                          |
|   | Sex        | Género del paciente                        |
|   | exang      | Angina inducida por ejercicio              |
|   | ca         | Número de vasos principales                |
|   | cp         | Tipo de Dolor de Pecho                     |
|   | trtbps     | Presión arterial en reposo                 |
|   | chol       | Colesterol en mg/dl                        |
|   | fbs        | Azúcar en sangre en ayunas                 |
|   | rest_ecg   | Resultados electrocardiográficos en reposo |
|   | thalach    | Frecuencia cardíaca máxima alcanzada       |
|   | target     | Riesgo de ataque cardíaco                  |

La compleja relación entre los datos complica la utilización de otros
métodos de análisis de datos, por lo que utilizar aprendizaje
supervisado es la opción mas prometedora.


* Conclusión
Durante esta practica aprendí que es aprendizaje supervisado, como
identificar un problema que se puede resolver mediante esta técnica y
como podemos utilizarla en los problemas que no se pueden resolver
mediante otras técnicas. 


* Referencias
\printbibliography[heading=none]

