
#+TITLE:  Elementos En La Organización De Una \\
#+TITLE:  Computadora De Propósito General

#+AUTHOR: Luis Eduardo Galindo Amaya \\
#+AUTHOR: 1274895 
#+DATE:   2022-08-14

#+LATEX_HEADER: \newcommand{\tagline}{Práctica 1}
#+OPTIONS: \n:nil num:nil toc:nil title:nil
#+LANGUAGE: es

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [12pt]
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{ a4paper, left=.75in, right=.75in, top=1in, bottom=1in }
#+LATEX_HEADER: \makeatletter


#+LATEX_HEADER: \newcommand{\asignatura}{Arquitectura de Computadoras (331)}
#+LATEX_HEADER: \newcommand{\docente}{Arturo Arreola Alvarez}

#+BEGIN_EXPORT latex
\begin{titlepage}
  \vspace*{0.75in}
  \begin{flushleft} 
	\sffamily      
    
	\large
    \tagline

	\Huge
    \@title \\
    \vspace{0.25in}
    \hline
    \vspace{0.25in}
	% \vspace{0.50in}

    \Large
    \@author
    
    
    \vspace*{\fill}
	
    \large
    \begin{tabular}{ |l|l| }
      \hline
      Asignatura & \asignatura \\
      Docente & \docente \\
      Fecha & \@date \\
      \hline
    \end{tabular} \\
\end{titlepage}

\setlength\parindent{0pt} 
% \maketitle
#+END_EXPORT

* Información De La Practica

** Objetivo
El alumno se familiarizará con la herramienta Marie.js para la ejecución de código en lenguaje ensamblador.

** Equipo                                                                 
Computadora personal con acceso a Internet.

** Desarrollo
- Ingrese a la página donde se encuentra la herramienta.

- Consulte la documentación y tutoriales de Marie, en especial las secciones Introduction to Marie y Marie Codes.      

- Escriba un código que solicite al usuario 2 números y despliegue el resultado de la ecuación 2x+3y–5.     

- Escriba un código que solicite 2 números y los reste. Desplegar un 1 si el resultado fue negativo o un 0 en caso contrario.       

- Realice capturas de pantalla donde se muestre el funcionamiento de los programas.       

- Realizar un reporte que incluya: 
  + Diagrama de bloques de una máquina de von Neumann y una breve descripción de cada componente.

  + Lista de las instrucciones de Marie y su y su función.

  + Describir el funcionamiento de los registros del Acumulador, Registro de instrucción, Contador del Programa, Registro de Acceso a Memoria (MAR), y Registro de Buffer de Memoria (MBR).

- Al entregar su práctica, adjunte los códigos de sus programas y su reporte.

